# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'cf1a36f0-271e-4b91-b828-92599fff59c6'
  
  # Web app name
  webAppName: 'johnswebapp-test2'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: 'johnswebapp-test'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  
  # Python version: 3.7
  pythonVersion: '3.7'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Sonarcloud'
        organization: 'garysca1'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'GarysCA1_GarysCA1'
        cliProjectName: 'GarysCA1'
        extraProperties: |
         sonar.exclusions= */antenv/*
      displayName: Prepare Analysis Config

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        curl 'https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip' --output build-wrapper.zip
        unzip build-wrapper.zip
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"
    - script: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        python -m pytest tests/ --junitxml=$(System.DefaultWorkingDirectory)/test.xml --cov=. --cov-report=html --cov-report=xml
      displayName: 'Running Unit Tests'
    - script: |
        python -m venv antenv
        source antenv/bin/activate
        pip install behave
        pip install selenium
        behave
      displayName: 'Running BDD Tests'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - task: SonarCloudAnalyze@1
      displayName: "Running Sonar Cloud Analysis"

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

